// Tests: OverviewHeroCard — 03-overview-hero FR1 + FR2
//
// FR1: OverviewHeroCard component: dual metrics with period window
//   SC1.1 — source renders $ + toLocaleString() earnings in colors.gold
//   SC1.2 — source renders Math.round(totalHours) + 'h' suffix in colors.textPrimary
//   SC1.3 — source imports Card and uses elevated prop
//   SC1.4 — source contains "LAST 4 WEEKS" and "LAST 12 WEEKS" strings
//   SC1.5 — source uses TouchableOpacity or Pressable for toggle
//   SC1.6 — source calls onWindowChange with 4
//   SC1.7 — source calls onWindowChange with 12
//   SC1.8 — active pill uses colors.surface background
//   SC1.9 — source has side-by-side row layout (flexDirection row)
//
// FR2: Overtime badge on hours metric
//   SC2.1 — source renders OT badge when overtimeHours > 0
//   SC2.2 — overtime badge uses overtimeWhiteGold color token
//   SC2.3 — overtime badge conditionally absent when overtimeHours === 0
//   SC2.4 — overtime value uses Math.round
//
// Strategy: Source-level static analysis (no React render — avoids native module mocking)

import * as path from 'path';
import * as fs from 'fs';

const HOURGLASSWS_ROOT = path.resolve(__dirname, '../../..');
const COMPONENT_FILE = path.join(HOURGLASSWS_ROOT, 'src', 'components', 'OverviewHeroCard.tsx');

// ─── FR1: Source analysis — earnings and hours formatting ─────────────────────

describe('OverviewHeroCard FR1 (03-overview-hero) — source: earnings/hours rendering', () => {
  it('SC1.1 — source contains $ prefix for earnings display', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/\$/);
  });

  it('SC1.1 — source uses toLocaleString() for earnings formatting', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/toLocaleString/);
  });

  it('SC1.1 — source uses colors.gold for earnings', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/colors\.gold/);
  });

  it('SC1.2 — source renders hours with "h" suffix', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    // Pattern: template literal or concat with 'h'
    expect(source).toMatch(/'h'|"h"|`.*h`|\+ 'h'|\+ "h"/);
  });

  it('SC1.2 — source uses colors.textPrimary for hours metric', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/colors\.textPrimary/);
  });

  it('SC1.2 — source uses Math.round for hours value', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/Math\.round.*totalHours|Math\.round.*hours/);
  });
});

// ─── FR1: Source analysis — Card container ────────────────────────────────────

describe('OverviewHeroCard FR1 (03-overview-hero) — source: Card container', () => {
  it('SC1.3 — imports Card component', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/import.*Card/);
  });

  it('SC1.3 — uses elevated prop on Card', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/elevated/);
  });
});

// ─── FR1: Source analysis — period label ─────────────────────────────────────

describe('OverviewHeroCard FR1 (03-overview-hero) — source: period label', () => {
  it('SC1.4 — contains "LAST 4 WEEKS" string', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/LAST 4 WEEKS/);
  });

  it('SC1.4 — contains "LAST 12 WEEKS" string', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/LAST 12 WEEKS/);
  });

  it('SC1.4 — period label is conditional on window value', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    // Must check window === 4 or window === 12
    expect(source).toMatch(/window\s*===\s*4|window\s*==\s*4/);
  });
});

// ─── FR1: Source analysis — 4W/12W toggle ────────────────────────────────────

describe('OverviewHeroCard FR1 (03-overview-hero) — source: 4W/12W toggle', () => {
  it('SC1.5 — uses TouchableOpacity or Pressable for toggle buttons', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/TouchableOpacity|Pressable/);
  });

  it('SC1.6 — calls onWindowChange when a toggle button is pressed', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    // Component uses map over [4, 12, 24] and calls onWindowChange(w) for each
    expect(source).toMatch(/onWindowChange\s*\(\s*w\s*\)/);
  });

  it('SC1.7 — toggle iterates over [4, 12, 24] windows', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    // The 4W/12W/24W toggle buttons are generated by mapping over this array
    expect(source).toMatch(/\[\s*4\s*,\s*12\s*,\s*24\s*\]/);
  });

  it('SC1.6 — 4W label present in source', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/4W/);
  });

  it('SC1.7 — 12W label present in source', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/12W/);
  });

  it('SC1.8 — active pill background uses colors.surface', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/colors\.surface/);
  });
});

// ─── FR1: Source analysis — layout ───────────────────────────────────────────

describe('OverviewHeroCard FR1 (03-overview-hero) — source: layout', () => {
  it('SC1.9 — uses flexDirection row for side-by-side metrics', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/flexDirection\s*:\s*['"]row['"]/);
  });
});

// ─── FR2: Source analysis — overtime badge ────────────────────────────────────

describe('OverviewHeroCard FR2 (03-overview-hero) — source: overtime badge', () => {
  it('SC2.1 — source contains "OT" text for overtime badge label', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/OT/);
  });

  it('SC2.1 — overtime badge rendered conditionally based on overtimeHours', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/overtimeHours/);
  });

  it('SC2.2 — overtime badge uses overtimeWhiteGold color', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/overtimeWhiteGold/);
  });

  it('SC2.3 — overtime badge is conditional (guarded by overtimeHours > 0)', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    // Pattern: overtimeHours > 0 as a conditional guard
    expect(source).toMatch(/overtimeHours\s*>\s*0/);
  });

  it('SC2.4 — overtime value uses Math.round', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    // Math.round applied to overtimeHours somewhere
    expect(source).toMatch(/Math\.round.*overtime|Math\.round.*Overtime/);
  });
});

// ─── FR1: File contract ───────────────────────────────────────────────────────

describe('OverviewHeroCard FR1 (03-overview-hero) — file contract', () => {
  it('OverviewHeroCard.tsx exists', () => {
    expect(fs.existsSync(COMPONENT_FILE)).toBe(true);
  });

  it('default exports OverviewHeroCard function', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/export default function OverviewHeroCard/);
  });

  it('accepts OverviewHeroCardProps', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/OverviewHeroCardProps/);
  });

  it('accepts totalEarnings prop', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/totalEarnings/);
  });

  it('accepts totalHours prop', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/totalHours/);
  });

  it('accepts window prop typed 4 | 12', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/window.*4\s*\|\s*12|4\s*\|\s*12.*window/);
  });

  it('accepts onWindowChange prop', () => {
    const source = fs.readFileSync(COMPONENT_FILE, 'utf8');
    expect(source).toMatch(/onWindowChange/);
  });
});
